config/routes.rb
Semblance::Application.routes.draw do

# highcharts
  match 'refinery/reports/screen1' => 'refinery/reports#screen_1'
  match 'my5/dashboard/screen1' => 'my5/dashboard#screen_1'
  match 'refinery/reports/update_department' => 'refinery/reports#update_department'
  match 'my5/dashboard/update_department' => 'my5/dashboard#update_department'
  match 'my5_naturally/search' => 'blog/posts#search'

#excel
  match 'refinery/reports/download_excel' => 'refinery/reports#download_excel'
  match 'my5/dashboard/download_excel' => 'my5/dashboard#download_excel'


  devise_for :customers, :controllers => { :registrations => 'customer_registrations', :sessions => 'customer_sessions' }
  devise_scope :customer do
    post '/customers/confirm_details' => 'customer_registrations#confirm_details', :as => :customer_confirm_details
    get '/customers/success' => 'customer_registrations#confirmed_sign_up', :as => :customer_confirmed_sign_up
    get '/customers/edit/billing_details' => 'customer_registrations#edit_billing_details', :as => :customer_edit_billing_details
    put '/customers/update_billing_details' => 'customer_registrations#update_billing_details', :as => :customer_update_billing_details
    put '/customers/remove_billing_details' => 'customer_registrations#remove_billing_details', :as => :customer_remove_billing_details
    post 'upload_image' => 'customer_registrations#upload_image', :as => :upload_image
  end

  resources :emails, :only => [:create]
  resources :main_page_contact_form, :only => :create


  namespace :my5 do
    namespace :dashboard do
      get 'customer'
      get 'reports'
    end
    resources :departments, :except => [:show]
    resources :health_checkins, :except => [:show, :edit, :update]
    resources :reminder_emails, :except => [:show]
  end

  namespace :refinery do
    resources :reports, :only => [:index, :show], :controller => 'reports'
  end

  match 'dashboard' => 'my5/dashboard#customer'

  match 'refinery/customers/bulk-import' => 'refinery/customers#bulk_import', :as => "bulk_import_customers"
  match 'refinery/video_stats' => 'refinery/video_stats#index', :as => "refinery_video_stats"

  if Rails.env.development?
    mount SubscriptionsMailer::Preview => 'subscriptions_mailer'
    mount ReminderEmailMailer::Preview => 'reminder_emails_mailer'
  end

  root :to => "pages#show", :id => "home"
end

app/controllers/admin/blog/categories_controller.rb
module Admin
  module Blog
    class CategoriesController < Admin::BaseController

      crudify :blog_category,
              :title_attribute => :title,
              :order => 'title ASC'

    end
  end
end

app/controllers/admin/blog/comments_controller.rb
module Admin
  module Blog
    class CommentsController < Admin::BaseController

      crudify :blog_comment,
              :title_attribute => :name,
              :order => 'published_at DESC'

      def index
        @blog_comments = BlogComment.unmoderated
        render :action => 'index'
      end

      def approved
        unless params[:id].present?
          @blog_comments = BlogComment.approved
          render :action => 'index'
        else
          @blog_comment = BlogComment.find(params[:id])
          @blog_comment.approve!
          flash[:notice] = t('approved', :scope => 'admin.blog.comments', :author => @blog_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

      def rejected
        unless params[:id].present?
          @blog_comments = BlogComment.rejected
          render :action => 'index'
        else
          @blog_comment = BlogComment.find(params[:id])
          @blog_comment.reject!
          flash[:notice] = t('rejected', :scope => 'admin.blog.comments', :author => @blog_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

    end
  end
end

app/controllers/admin/blog/posts_controller.rb
module Admin
  module Blog
    class PostsController < Admin::BaseController
      require 'will_paginate/array'
      
      crudify :blog_post,
              :title_attribute => :title,
              :order => 'published_at DESC'
          
      def uncategorized
        @blog_posts = BlogPost.uncategorized.paginate({
          :page => params[:page],
          :per_page => BlogPost.per_page
        })
      end
  
      def tags
        op =  case ActiveRecord::Base.connection.adapter_name.downcase
              when 'postgresql'
                '~*'
              else
                'LIKE'
              end
        wildcard =  case ActiveRecord::Base.connection.adapter_name.downcase
                    when 'postgresql'
                      '.*'
                    else
                      '%'
                    end
        @tags = BlogPost.tag_counts_on(:tags).where(
            ["tags.name #{op} ?", "#{wildcard}#{params[:term].to_s.downcase}#{wildcard}"]
          ).map { |tag| {:id => tag.id, :value => tag.name}}
        render :json => @tags.flatten
      end
  
      def create
        p "a"*100
        p @blog_categories
        # if the position field exists, set this object as last object, given the conditions of this class.
        if BlogPost.column_names.include?("position")
          params[:blog_post].merge!({
            :position => ((BlogPost.maximum(:position, :conditions => "")||-1) + 1)
          })
        end
    
        if BlogPost.column_names.include?("user_id")
          params[:blog_post].merge!({
            :user_id => current_user.id
          })
        end

        if (@blog_post = BlogPost.create(params[:blog_post])).valid?
          (request.xhr? ? flash.now : flash).notice = t(
            'refinery.crudify.created',
            :what => "'#{@blog_post.title}'"
          )

          unless from_dialog?
            unless params[:continue_editing] =~ /true|on|1/
              redirect_back_or_default(admin_blog_posts_url)
            else
              unless request.xhr?
                redirect_to :back
              else
                render :partial => "/shared/message"
              end
            end
          else
            render :text => "<script>parent.window.location = '#{admin_blog_posts_url}';</script>"
          end
        else
          unless request.xhr?
            render :action => 'new'
          else
            render :partial => "/shared/admin/error_messages",
                   :locals => {
                     :object => @blog_post,
                     :include_object_name => true
                   }
          end
        end
      end

      before_filter :find_all_categories,
                    :only => [:new, :edit, :create, :update]

      before_filter :check_category_ids, :only => :update

    protected
      def find_all_categories
        @blog_categories = BlogCategory.all
      end

      def check_category_ids
        params[:blog_post][:category_ids] ||= []
      end
    end
  end
end

app/controllers/admin/blog/settings_controller.rb
module Admin
  module Blog
    class SettingsController < Admin::BaseController

      def notification_recipients
        @recipients = BlogComment::Notification.recipients

        if request.post?
          BlogComment::Notification.recipients = params[:recipients]
          flash[:notice] = t('updated', :scope => 'admin.blog.settings.notification_recipients',
                             :recipients => BlogComment::Notification.recipients)
          unless request.xhr? or from_dialog?
            redirect_back_or_default(admin_blog_posts_path)
          else
            render :text => "<script type='text/javascript'>parent.window.location = '#{admin_blog_posts_path}';</script>",
                   :layout => false
          end
        end
      end

      def moderation
        enabled = BlogComment::Moderation.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_blog_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

      def comments
        enabled = BlogComment.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_blog_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end
      
      def teasers
        enabled = BlogPost.teaser_enabled_toggle!
        unless request.xhr?
          redirect_back_or_default(admin_blog_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

    end
  end
end

app/controllers/blog/categories_controller.rb
module Blog
  class CategoriesController < BlogController

    layout 'customer'
    before_filter :authenticate_customer!

    def show
      @category = BlogCategory.find(params[:id])
      @blog_posts = @category.posts.live.includes(:comments, :categories).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 6)
      })
    end

  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    layout 'customer'
    before_filter :authenticate_customer!
    before_filter :find_all_blog_posts
    before_filter :find_blog_post, :only => [:show, :comment, :update_nav]
    before_filter :find_tags
    before_filter :customer_views, :only => %w{ show index }

    helper :blog

    respond_to :html, :js, :rss

    def index
      # Rss feeders are greedy. Let's give them every blog post instead of paginating.
      (@blog_posts = BlogPost.live.includes(:comments, :categories).all) if request.format.rss?
      respond_with (@blog_posts) do |format|
        format.html
        format.rss
      end
    end

    def show
      @blog_comment = BlogComment.new
      @canonical = url_for(:locale => ::Refinery::I18n.default_frontend_locale) if canonical?

      respond_with (@blog_post) do |format|
        format.html { present(@blog_post) }
        format.js { render :partial => 'post', :layout => false }
      end
    end

    def comment
      if (@blog_comment = @blog_post.comments.create(params[:blog_comment])).valid?
        if BlogComment::Moderation.enabled? or @blog_comment.ham?
          begin
            Blog::CommentMailer.notification(@blog_comment, request).deliver
          rescue
            logger.warn "There was an error delivering a blog comment notification.\n#{$!}\n"
          end
        end

        if BlogComment::Moderation.enabled?
          flash[:notice] = t('thank_you_moderated', :scope => 'blog.posts.comments')
          redirect_to blog_post_url(params[:id])
        else
          flash[:notice] = t('thank_you', :scope => 'blog.posts.comments')
          redirect_to blog_post_url(params[:id],
                                    :anchor => "comment-#{@blog_comment.to_param}")
        end
      else
        render :action => 'show'
      end
    end

    def archive
      if params[:month].present?
        date          = "#{params[:month]}/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title   = @archive_date.strftime('%B %Y')
        @blog_posts   = BlogPost.live.by_archive(@archive_date).paginate({
                                                                             :page     => params[:page],
                                                                             :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 6)
                                                                         })
      else
        date          = "01/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title   = @archive_date.strftime('%Y')
        @blog_posts   = BlogPost.live.by_year(@archive_date).paginate({
                                                                          :page     => params[:page],
                                                                          :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 6)
                                                                      })
      end
      respond_with (@blog_posts)
    end

    def tagged
      @tag        = ActsAsTaggableOn::Tag.find(params[:tag_id])
      @tag_name   = @tag.name
      @blog_posts = BlogPost.tagged_with(@tag_name).paginate({
                                                                 :page     => params[:page],
                                                                 :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 6)
                                                             })
    end

    def search
      posts  = BlogPost.where("title LIKE '%#{params[:search]}%' OR body LIKE '%#{params[:search]}%' OR custom_teaser LIKE '%#{params[:search]}%' ")
      @posts = posts.paginate({
                                  :page     => params[:page],
                                  :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 6)
                              })
    end

    protected

    def find_blog_post
      unless (@blog_post = BlogPost.find(params[:id])).try(:live?)
        if refinery_user? and current_user.authorized_plugins.include?("refinerycms_blog")
          @blog_post = BlogPost.find(params[:id])
        else
          error_404
        end
      end
    end

    def find_all_blog_posts
      @blog_posts = BlogPost.live.includes(:comments, :categories).paginate({
                                                                                :page     => params[:page],
                                                                                :per_page => RefinerySetting.set(:blog_posts_per_page, 5)
                                                                            })
      @recent_posts = @blog_posts.first(5)
    end

    def find_tags
      @tags = BlogPost.tag_counts_on(:tags)
    end

    def canonical?
      ::Refinery.i18n_enabled? && ::Refinery::I18n.default_frontend_locale != ::Refinery::I18n.current_frontend_locale
    end
  end
end

app/helpers/blog_helper.rb
module BlogHelper

  def blog_list_archive
    posts = BlogPost.live.select('published_at').all_previous
    return nil if posts.blank?
    html  = '<ul class="categories_list" id="archived_posts">'
    links = []
    years = []

    posts.each do |e|
      links << e.published_at.strftime('%m/%Y')
      years << e.published_at.strftime('%Y')
    end

    years.uniq!
    links.uniq!

    years.each do |year|
      months = []
      links.each do |l|
        months << l.split('/')[0] if l.split('/')[1] == year
      end
      html << '<li class="li_year item" >'
      html << year
      html << '<ul style="display:none" class="subcat" >'
      months.each do |m|
        count = BlogPost.live.by_archive(Time.parse(m + '/' + year)).size
        text  = t('date.month_names')[m.to_i] + "(#{count})"
        html << "<li class='item'>"
        html << link_to(text, archive_blog_posts_path(:year => year, :month => m))
        html << '</li>'
      end
      html << '</ul>'
      html << '</li>'
    end
    html << '</ul>'

    html.html_safe
  end

  def list_recent_articles
    blog_visits = current_customer.customer_visits.where(:controller_name => 'blog/posts', :action_name => 'show').last(5)
    html        = '<ul class="categories_list" id="recent_articles">'
    blog_visits.each do |bv|
      html << "<li class='item'>"
      html << link_to("#{bv.conditions}", blog_post_path(bv.show_id))
      html << '</li>'
    end
    html << '</ul>'
    html.html_safe
  end

  def blog_post_teaser_enabled?
    BlogPost.teasers_enabled?
  end

  def post_teaser(post,length)
    if post.respond_to?(:custom_teaser) && post.custom_teaser.present?
      post.custom_teaser.html_safe
    else
      truncate(post.body, {
          :length =>  length,
          :preserve_html_tags => true
      }).html_safe
    end
  end
end

app/views/blog/posts/_comment.html.erb
<article class='blog_comment_message' id='<%= "comment-#{comment.to_param}" %>'>
  <%= image_tag comment.avatar_url, :alt => comment.name, :class => 'avatar' %>
  <%= simple_format auto_link(comment.message.to_s) %>
  <footer class='blog_comment_author'>
    <p>
      <%= t('by', :scope => 'blog.posts.comments', :who => comment.name) %>,
      <%= t('time_ago', :scope => 'blog.posts.comments', :time => time_ago_in_words(comment.created_at)) %>
    </p>
  </footer>
</article>

app/views/blog/posts/_nav.html.erb
<nav id="next_prev_article">
  <% if @blog_post.next.present? -%>
    <%= link_to (truncate(@blog_post.next.title) + " &#187;").html_safe, @blog_post.next, :class => 'next' %>
  <% end -%>

  <%= link_to t('blog_home', :scope => 'blog.posts.show'), blog_root_path, :class => 'home' %>

  <% if @blog_post.prev.present? -%>
    <%= link_to ("&#171; " + truncate(@blog_post.prev.title)).html_safe, @blog_post.prev, :class => 'prev' %>
  <% end -%>
</nav><!-- /next_prev_article -->

app/views/blog/posts/archive.html.erb
<% content_for :body_content_left do %>
    <%= raw @page[Page.default_parts.first.to_sym] if Page.default_parts.any? %>
    <%= render 'blog/shared/blog_title' %>
    <h1 class="blog_title"> Archive <%= @date_title %> </h1>

    <% if @blog_posts.any? %>
        <section id="blog_blog_posts">
          <%= render :partial => "/blog/shared/post", :collection => @blog_posts %>
          <%= will_paginate @blog_posts %>
        </section>

    <% else %>
        <p><%= t('.no_blog_articles_yet') %></p>
    <% end %>
<% end %>

<% content_for :body_content_right do %>
    <div class="sidebar_section_wrap logo">
      <img src="/images/blog/my_five.jpg" alt="" />
    </div>
    <%= form_tag my5_naturally_search_path, :class => 'search_form' do %>
        <%= search_field_tag('search', nil, :placeholder => 'Enter search term...', :class => 'search_input') %>
        <%= submit_tag 'Ok', :class => 'button search_button' %>
    <% end %>
    <%= raw @page[Page.default_parts.second.to_sym] if Page.default_parts.many? %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/categories" %>
    </div>
    <% if current_customer.customer_visits.any? %>
        <div class="sidebar_section_wrap">
          <%= render :partial => 'blog/shared/related_posts' %>
        </div>
    <% end %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/archive_list" %>
    </div>
<% end %>

<%= render :partial => "/shared/content_page", :locals => { :remove_automatic_sections => true }  %>

app/views/blog/posts/index.html.erb
<% content_for :body_content_left do %>
    <%= raw @page[Page.default_parts.first.to_sym] if Page.default_parts.any? %>
    <%= render 'blog/shared/blog_title' %>
    <% if @blog_posts.any? %>
        <section id="blog_posts">
          <%= render :partial => "/blog/shared/post", :collection => @blog_posts %>
          <%= will_paginate @blog_posts %>
        </section>

    <% else %>
        <p><%= t('.no_blog_articles_yet') %></p>
    <% end %>
<% end %>

<% content_for :body_content_right do %>
    <div class="sidebar_section_wrap logo">
      <img src="/images/blog/my_five.jpg" alt=""/>
    </div>
    <%= form_tag my5_naturally_search_path, :class => 'search_form' do %>
        <%= search_field_tag('search', nil, :placeholder => 'Enter search term...', :class => 'search_input') %>
        <%= submit_tag 'Ok', :class => 'button search_button' %>
    <% end %>
    <%= raw @page[Page.default_parts.second.to_sym] if Page.default_parts.many? %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/categories" %>
    </div>
    <% if current_customer.customer_visits.any? %>
        <div class="sidebar_section_wrap">
          <%= render :partial => 'blog/shared/related_posts' %>
        </div>
    <% end %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/archive_list" %>
    </div>
<% end %>

<%= render :partial => "/shared/content_page", :locals => { :remove_automatic_sections => true } %>
<% content_for :stylesheets, stylesheet_link_tag('refinerycms-blog') %>

app/views/blog/posts/search.html.erb
<% content_for :body_content_left do %>
    <%= raw @page[Page.default_parts.first.to_sym] if Page.default_parts.any? %>
    <%= render 'blog/shared/blog_title' %>
    <h1 class="blog_title"> Search Results </h1>

    <% if @posts.any? %>
        <section id="blog_posts">
          <%= render :partial => "/blog/shared/post", :collection => @posts %>
          <%= will_paginate @posts %>
        </section>

    <% else %>
        <p><%= t('.no_blog_articles_yet') %></p>
    <% end %>
<% end %>

<% content_for :body_content_right do %>
    <div class="sidebar_section_wrap logo">
      <img src="/images/blog/my_five.jpg" alt=""/>
    </div>
    <%= form_tag my5_naturally_search_path, :class => 'search_form' do %>
        <%= search_field_tag('search', nil, :placeholder => 'Enter search term...', :class => 'search_input') %>
        <%= submit_tag 'Ok', :class => 'button search_button' %>
    <% end %>
    <%= raw @page[Page.default_parts.second.to_sym] if Page.default_parts.many? %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/categories" %>
    </div>
    <% if current_customer.customer_visits.any? %>
        <div class="sidebar_section_wrap">
          <%= render :partial => 'blog/shared/related_posts' %>
        </div>
    <% end %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/archive_list" %>
    </div>
<% end %>

<%= render :partial => "/shared/content_page", :locals => { :remove_automatic_sections => true } %>

app/views/blog/posts/show.html.erb
<% content_for :body_content_left do %>
    <%= raw @page[Page.default_parts.first.to_sym] if Page.default_parts.any? %>
    <%= render 'blog/shared/blog_title' %>

    <% if @blog_posts.any? %>
        <div id="show_blog_post">
          <% flash.each do |key, value| %>
              <div id='flash' class="flash flash_<%= key %>">
                <%= value %>
              </div>
          <% end %>
          <article id="blog_post">
            <header>
              <h1><%= @blog_post.title %></h1>
              <section class='details'>
                <time datetime="<%= l @blog_post.published_at.to_date, :format => :default %>" class='posted_at'>
                  <%= t('created_at', :scope => 'blog.shared.posts', :when => l(@blog_post.published_at.to_date, :format => :short)) %>
                </time>
                <%= "#{t('by', :scope => 'blog.posts.show')} #{@blog_post.author.username}" if @blog_post.author.present? %>
                .
                <% if (categories = @blog_post.categories).any? %>
                    <aside class='filed_in'>
                      <%= t('filed_in', :scope => 'blog.posts.show') %>
                      <% categories.each_with_index do |category, index| %>
                          <%= link_to category.title, blog_category_url(category) -%><%= ',' if index < ((categories.length) - 1) %>
                      <% end %>
                    </aside>
                <% end %>
              </section>
            </header>
            <%= @blog_post.body.html_safe %>

            <% if BlogPost::ShareThis.enabled? %>
                <span class="st_sharethis" displayText="ShareThis"></span>
            <% end %>
          </article>
          <%= render :partial => '/shared/draft_page_message' unless @blog_post.nil? or @blog_post.live? -%>
        </div>

        <% if BlogPost.comments_allowed? %>
            <div class="comment_button">
              <div class="comment_icon"></div>
              <% comments_count = @blog_post.comments.count %>
              <div class="comment_counter"><%= pluralize(comments_count, "Comment") if comments_count > 0 %></div>
            </div>

            <div class="print_button">
              <div class="print_icon"></div>
              <div class="print_link">Print</div>
            </div>

            <aside id="comments" style="display: none">
              <h2><%= t('.comments.title') %></h2>
              <% if (comments = @blog_post.comments.approved).any? %>
                  <%= render :partial => "comment", :collection => comments %>
              <% else %>
                  <p>
                    <%= t('none', :scope => 'blog.shared.comments') %>.
                  </p>
              <% end %>

              <% flash.each do |key, value| %>
                  <div id='flash' class="flash flash_<%= key %>">
                    <%= value %>
                  </div>
              <% end %>

              <h2><%= t('.comments.add') %></h2>
              <%= form_for [:blog_post, @blog_comment] do |f| %>
                  <%= render :partial => "/shared/admin/error_messages",
                             :locals  => {
                                     :object              => f.object,
                                     :include_object_name => true
                             } %>
                  <div class='field'>
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                  </div>
                  <div class='field'>
                    <%= f.label :email %>
                    <%= f.email_field :email %>
                  </div>
                  <div class='field message_field'>
                    <%= f.label :message %>
                    <%= f.text_area :message, :rows => 6 %>
                  </div>
                  <div class='field form-actions'>
                    <%= f.submit t('.submit') %>
                  </div>
              <% end %>
            </aside>
        <% end %>

    <% else %>
        <p><%= t('.no_blog_articles_yet') %></p>
    <% end %>
<% end %>

<% content_for :body_content_right, :style => 'margin-top: -99px; border-left: 1px solid #b0b1b3;' do %>
    <div class="sidebar_section_wrap logo">
      <img src="/images/blog/my_five.jpg" alt=""/>
    </div>
    <%= form_tag my5_naturally_search_path, :class => 'search_form' do %>
        <%= search_field_tag('search', nil, :placeholder => 'Enter search term...', :class => 'search_input') %>
        <%= submit_tag 'Ok', :class => 'button search_button' %>
    <% end %>
    <%= raw @page[Page.default_parts.second.to_sym] if Page.default_parts.many? %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/categories" %>
    </div>
    <% if current_customer.customer_visits.any? %>
        <div class="sidebar_section_wrap">
          <%= render :partial => 'blog/shared/related_posts' %>
        </div>
    <% end %>
    <div class="sidebar_section_wrap">
      <%= render :partial => "/blog/shared/archive_list" %>
    </div>
<% end %>

<%= render :partial => "/shared/content_page", :locals => { :remove_automatic_sections => true } %>
<% content_for :stylesheets, stylesheet_link_tag('refinerycms-blog') %>
<% content_for :before_javascript_libraries, jquery_include_tags(:jquery_ui => false) %>
<% content_for :javascripts do %>
    <%# enable AJAX'd post nav at your own risk until html5 history API implemented. %>
    <%#= javascript_include_tag('refinerycms-blog') %>
    <script src="http://w.sharethis.com/button/buttons.js"></script>
    <script>stLight.options({publisher: '<%= BlogPost::ShareThis.key %>'});</script>
<% end if BlogPost::ShareThis.enabled? %>

app/views/blog/posts/tagged.html.erb
<% content_for :body_content_title, "#{t('.posts_tagged')} &#8220;#{@tag_name.titleize}&#8221;".html_safe -%>

<% content_for :body_content_left do %>
    <%= render 'blog/shared/blog_title' %>
    <% if @blog_posts.any? %>
        <section id="blog_posts">
          <%= render :partial => "/blog/shared/post", :collection => @blog_posts %>
          <%= will_paginate @blog_posts %>
        </section>
    <% else %>
        <p><%= t('.no_blog_articles_yet') %></p>
    <% end %>
<% end %>

<% content_for :body_content_right do %>
    <%= render :partial => "/blog/shared/categories" %>
    <%= render :partial => "/blog/shared/tags" %>
    <%= render :partial => "/blog/shared/rss_feed" %>
    <%= render :partial => "/blog/shared/archive_list" %>
<% end %>

<%= render :partial => "/shared/content_page" %>
<% content_for :stylesheets, stylesheet_link_tag('refinerycms-blog') %>