config/routes.rb
Semblance::Application.routes.draw do

# highcharts
  match 'refinery/reports/screen1' => 'refinery/reports#screen_1'
  match 'my5/dashboard/screen1' => 'my5/dashboard#screen_1'
  match 'refinery/reports/update_department' => 'refinery/reports#update_department'
  match 'my5/dashboard/update_department' => 'my5/dashboard#update_department'
  match 'my5_naturally/search' => 'blog/posts#search'

#excel
  match 'refinery/reports/download_excel' => 'refinery/reports#download_excel'
  match 'my5/dashboard/download_excel' => 'my5/dashboard#download_excel'


  devise_for :customers, :controllers => { :registrations => 'customer_registrations', :sessions => 'customer_sessions' }
  devise_scope :customer do
    post '/customers/confirm_details' => 'customer_registrations#confirm_details', :as => :customer_confirm_details
    get '/customers/success' => 'customer_registrations#confirmed_sign_up', :as => :customer_confirmed_sign_up
    get '/customers/edit/billing_details' => 'customer_registrations#edit_billing_details', :as => :customer_edit_billing_details
    put '/customers/update_billing_details' => 'customer_registrations#update_billing_details', :as => :customer_update_billing_details
    put '/customers/remove_billing_details' => 'customer_registrations#remove_billing_details', :as => :customer_remove_billing_details
    post 'upload_image' => 'customer_registrations#upload_image', :as => :upload_image
  end

  resources :emails, :only => [:create]
  resources :main_page_contact_form, :only => :create


  namespace :my5 do
    namespace :dashboard do
      get 'customer'
      get 'reports'
    end
    resources :departments, :except => [:show]
    resources :health_checkins, :except => [:show, :edit, :update]
    resources :reminder_emails, :except => [:show]
  end

  namespace :refinery do
    resources :reports, :only => [:index, :show], :controller => 'reports'
  end

  match 'dashboard' => 'my5/dashboard#customer'

  match 'refinery/customers/bulk-import' => 'refinery/customers#bulk_import', :as => "bulk_import_customers"
  match 'refinery/video_stats' => 'refinery/video_stats#index', :as => "refinery_video_stats"

  if Rails.env.development?
    mount SubscriptionsMailer::Preview => 'subscriptions_mailer'
    mount ReminderEmailMailer::Preview => 'reminder_emails_mailer'
  end

  root :to => "pages#show", :id => "home"
end

app/views/admin/_head.html.erb
<head>
  <meta charset='<%= ::Refinery::Application.config.encoding %>'/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <%= yield :meta %>
  <title><%= RefinerySetting.find_or_set(:site_name, 'Company Name') -%> - Refinery</title>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag 'refinery/site_bar',
                          'refinery/refinery',
                          'refinery/ui',
                          'refinery/submenu',
                          'refinery/tooltips',
                          'wymeditor/skins/refinery/skin',
                          'refinery/my5_custom',
                          'ui.dropdownchecklist.standalone',
                          :cache => ("cache/refinery" if Rails.root.writable? and
                                  RefinerySetting.find_or_set(:use_resource_caching, true) and
                                  request.env['HTTP_USER_AGENT'] !~ /MSIE/) -%>

  <%= yield :stylesheets %>

  <%= javascript_include_tag 'modernizr-min' %>
  <script>
      var _bugHerdAPIKey = '9b4d1851-3fa6-4117-812a-bf74418a4a36';
      (function (d, t) {
          var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
          bh.type = 'text/javascript';
          bh.src = "//www.bugherd.com/bugherd.js?";
          s.parentNode.insertBefore(bh, s);
      })(document, 'script');

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-26361746-1']);
      _gaq.push(['_trackPageview']);
      ddsmoothmenu.init({
          mainmenuid: "smoothmenu",
          orientation: 'h',
          classname: 'ddsmoothmenu',
          contentsource: "markup"
      });

  </script>
</head>

app/views/admin/_javascripts.html.erb
<%
   js_caching = Rails.root.writable? and RefinerySetting.find_or_set(:use_resource_caching, true)
   login = login? unless defined?(login)
-%>
<%= yield :before_javascript_libraries -%>
<%= javascript_include_tag 'refinery/i18n' -%>
<script>I18n.locale = '<%= I18n.locale %>';</script>
<%= javascript_include_tag 'translations' if Rails.root.join('public', 'javascripts', 'translations.js').exist? -%>
<%= jquery_include_tags    :caching => js_caching -%>

<%= javascript_include_tag 'rails.js' %>

<%= javascript_include_tag 'jquery/jquery.corner.js',
                           'jquery/jquery.textTruncate.js',
                           'jquery/jquery.html5-placeholder-shim.js',
                           'jquery/jquery.timers.js',
                           'jquery/jquery.jcarousel.js',
                           'refinery/ui.dropdownchecklist-1.4-min.js',
                           'blog/blog',
                           :cache => ("cache/jquery-plugins" if js_caching) -%>

<%= javascript_include_tag 'jquery.refinery.wymeditor.fix.js', 'admin' %>

<%= yield :after_javascript_libraries -%>
<%= javascript_include_tag 'refinery/boot_wym',
                           'refinery/core',
                           'refinery/site_bar',
                           'refinery/admin',
                           'refinery/submenu',
                           :cache => ("cache/admin" if js_caching) unless login -%>
<%= javascript_include_tag 'refinery/core' if login -%>

<%= yield :javascripts -%>

app/views/admin/_menu.html.erb
<% content_for :stylesheets do %>
    hi
<% end %>

<nav id="menu">
  <% Refinery::Plugins.active.in_menu.each do |plugin| -%>
      <% unless plugin.title == "Files" || plugin.title == "programs" || plugin.title == "Settings" || plugin.title == "Subscriptions" %>

          <!-- This is custom code that define the various special colours for the menu items -->
          <% file_mgmt = (plugin.title == "Videos" || plugin.title == "Audios") ? true : false %>
          <% user_mgmt = (plugin.title == "Customers" || plugin.title == "Corporations") ? true : false %>
          <% core_content = (plugin.title == "Symptomatics" || plugin.title == "My Eqs" || plugin.title == "Mini Modules" || plugin.title == "Audio Programs") ? true : false %>
          <!-- End custom code -->

          <%= link_to plugin.title, plugin.url,
                      :class => "#{(plugin.highlighted?(params) ? 'active' : '')} #{'orange' if core_content} #{'green' if user_mgmt} #{'blue' if file_mgmt}",
                      :id    => "plugin_#{plugin.name}" %>
      <% end %>
  <% end -%>

  <!-- This is custom code to insert our custom reports menu into the CMS -->
  <%= link_to "Reports", refinery_reports_url, :id => "plugin_reports", :class => "#{'active' if request.url == refinery_reports_url}" %>
  <!-- End custom code -->

  <% if Refinery::Plugins.active.in_menu.many? -%>
      <%= link_to refinery_icon_tag('arrow_switch.png'), "",
                  :id    => "menu_reorder",
                  :title => t('.reorder_menu') %>

      <%= link_to refinery_icon_tag('tick.png'), "",
                  :id    => "menu_reorder_done",
                  :title => t('.reorder_menu_done'),
                  :style => "display: none;" %>
  <% end %>
</nav>