config/routes.rb
Semblance::Application.routes.draw do

# highcharts
  match 'refinery/reports/screen1' => 'refinery/reports#screen_1'
  match 'my5/dashboard/screen1' => 'my5/dashboard#screen_1'
  match 'refinery/reports/update_department' => 'refinery/reports#update_department'
  match 'my5/dashboard/update_department' => 'my5/dashboard#update_department'
  match 'my5_naturally/search' => 'blog/posts#search'

#excel
  match 'refinery/reports/download_excel' => 'refinery/reports#download_excel'
  match 'my5/dashboard/download_excel' => 'my5/dashboard#download_excel'


  devise_for :customers, :controllers => { :registrations => 'customer_registrations', :sessions => 'customer_sessions' }
  devise_scope :customer do
    post '/customers/confirm_details' => 'customer_registrations#confirm_details', :as => :customer_confirm_details
    get '/customers/success' => 'customer_registrations#confirmed_sign_up', :as => :customer_confirmed_sign_up
    get '/customers/edit/billing_details' => 'customer_registrations#edit_billing_details', :as => :customer_edit_billing_details
    put '/customers/update_billing_details' => 'customer_registrations#update_billing_details', :as => :customer_update_billing_details
    put '/customers/remove_billing_details' => 'customer_registrations#remove_billing_details', :as => :customer_remove_billing_details
    post 'upload_image' => 'customer_registrations#upload_image', :as => :upload_image
  end

  resources :emails, :only => [:create]
  resources :main_page_contact_form, :only => :create


  namespace :my5 do
    namespace :dashboard do
      get 'customer'
      get 'reports'
    end
    resources :departments, :except => [:show]
    resources :health_checkins, :except => [:show, :edit, :update]
    resources :reminder_emails, :except => [:show]
  end

  namespace :refinery do
    resources :reports, :only => [:index, :show], :controller => 'reports'
  end

  match 'dashboard' => 'my5/dashboard#customer'

  match 'refinery/customers/bulk-import' => 'refinery/customers#bulk_import', :as => "bulk_import_customers"
  match 'refinery/video_stats' => 'refinery/video_stats#index', :as => "refinery_video_stats"

  if Rails.env.development?
    mount SubscriptionsMailer::Preview => 'subscriptions_mailer'
    mount ReminderEmailMailer::Preview => 'reminder_emails_mailer'
  end

  root :to => "pages#show", :id => "home"
end

app/controllers/customer_registrations_controller.rb
class CustomerRegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_customer!, :only => [:upload_image]
  before_filter :force_ssl

  def new
    if session[:new_customer] && session[:new_customer].any?
      session[:new_customer].delete(:credit_card)
      session[:new_customer].delete(:password)
      session[:new_customer].delete(:password_confirmation)

      self.resource = Customer.new(session[:new_customer])
    elsif self.resource.nil?
      self.resource = Customer.new
    end
  end


  def confirm_details
    session[:new_customer] = params[:customer]
    self.resource = Customer.new(session[:new_customer])

    # To populate all error fields
    is_valid = self.resource.valid?
    is_valid = self.resource.validate_credit_card_information(params[:customer][:credit_card]) && is_valid

    if is_valid
      @customer_details = session[:new_customer]
    else
      render :new
    end
  end

  def create
    credit_card = session[:new_customer].delete(:credit_card)
    self.resource = Customer.new(session[:new_customer])

    if self.resource.valid? # !credit_card.blank? && 
      if self.resource.store_eway_customer(credit_card) && resource.save
        session.delete(:new_customer)

        if resource.active_for_authentication?
          if self.resource.free_trial_opted?
            Subscription.free_trial_for(resource.id, 10.days).save
            SubscriptionsMailer.joined(self.resource).deliver
          else
            self.resource.process_payment
          end

          set_flash_message :notice, :signed_up if is_navigational_format?
          sign_in(resource_name, resource)

          respond_with resource, :location => customer_confirmed_sign_up_url #after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :inactive_signed_up, :reason => inactive_reason(resource) if is_navigational_format?
          expire_session_data_after_sign_in!

          respond_with resource, :location => customer_confirmed_sign_up_url #after_inactive_sign_up_path_for(resource)
        end
      else
        flash[:alert] = "There was an error processing your credit card details, please try again."
        clean_up_passwords(resource)
        respond_with_navigational(resource) { render_with_scope :new }
      end
    else
      clean_up_passwords(resource)
      respond_with_navigational(resource) { render_with_scope :new }
    end
  end

  def confirmed_sign_up
    render :layout => "customer"
  end

  def upload_image
    unless params[:customer] && current_customer.update_attributes(params[:customer]) && current_customer.save(:validate => false)
        @error = true
    end
    redirect_to :action => "edit"
  end

  def edit_billing_details
    render :layout => "customer"
  end

  def update_billing_details
    credit_card = params[:customer].delete(:credit_card)
    if current_customer.update_attributes(params[:customer]) && current_customer.store_eway_customer(credit_card) && current_customer.save
      redirect_to edit_customer_registration_path, :notice => 'Billing details updated!'
    else
      render :action => 'edit_billing_details', :alert => 'Unable to store your billing details'
    end
  end

  def remove_billing_details
    customer = current_customer

    customer.eway_token = customer.street_1 = customer.street_2 = customer.city = customer.state = customer.country = customer.zip_code = customer.card_number = customer.card_expiry_date = nil

    if customer.save
      redirect_to edit_customer_registration_path, :notice => 'Billing details removed!'
    else
      redirect_to edit_customer_registration_path, :alert => 'Unable to remove billing details.'
    end

  end
end

app/views/customer_registrations/confirmed_sign_up.html.haml
.padded
	%h3 Welcome to My 5
	- if current_customer.free_trial_opted?
		%p
			Thanks for signing up to our
			%b free 10-day trial.
			At the end of 10 days, if you don't cancel, we'll bill your credit card for $#{Program.first.try(:price)}, a year's subscription to My 5. Enjoy!
	- else
		%p
			Thanks for signing up to our 1 year subscription. we'll bill your credit card for $#{Program.first.try(:price)},
			a year's subscription to My 5. Enjoy!

	%p
		= link_to 'Continue to My 5', my5_dashboard_customer_url

app/views/customer_registrations/edit.html.haml
- content_for :extra_stylesheets do
  = stylesheet_link_tag "my5/base"

.content_left
  .padded
    %h1 Edit my account

    = semantic_form_for(resource, :as => resource_name, :url => upload_image_path, :html => { :multipart => true, :method => :post }, :remote => true) do |f|
      %li.avatar_section
        / This is a bit hacky, but it's hard to find an alternative without altering Paperclip or Formtastic.  Something to raise on Github.
        .img{:style => "background: url('#{Customer.find(resource.id).avatar.url(:thumb)}') no-repeat center;"}
        = f.label :avatar, "Display picture"
        = f.file_field :avatar
        %br
        = f.submit "Upload"
    - p 'a'*100; p resource
    .clearfix
    = semantic_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :multipart => true, :method => :put }) do |f|

      .clearfix
      %li
        %label Reminder emails
        .reminder_emails
          - if current_customer.reminders.empty?
            = link_to "Setup my reminder emails", my5_reminder_emails_path
          - else
            %b You have #{current_customer.reminders.count} active reminders.
            %br
            = link_to "Edit my reminder emails", my5_reminder_emails_path
      - if current_customer.retail?
        %li
          = f.label "Subscription"
          .subscription
            - subscription = current_customer.subscriptions.active_subscription.first
            
            - if subscription
              You are currently using My 5 #{subscription.free_trial? ? "within the Free Trial" : "with a Yearly subscription"} period, which ends on
              %b #{subscription.expiry_date_to_s}.
            - else
              You are currently using My 5 as part of a corporate plan.
      -#%li
      -#  = f.label :renew_subscription, 'Automatically Renew Subscription', :class => "double-line"
      -#  = f.check_box :renew_subscription
      .clearfix
      %h3 Personal details
      = f.input :first_name, :required => true
      = f.input :last_name, :required => true
      = f.input :email, :required => true
      = f.input :title, :collection => ['Mr.', 'Ms.', 'Mrs.', 'Miss', 'Dr.', 'Sir.', 'Prof.'], :include_blank => false, :input_html => {:class => "short"}, :required => true
      = f.input :department_id, :label => "Department", :required => true
      = f.input :role, :required => true

      = f.input :street_1, :required => true
      = f.input :street_2
      = f.input :contact_phone
      = f.input :city, :label => 'Suburb', :required => true
      = f.input :state, :label => 'City' , :required => true
      = f.input :state2, :label => 'State' ,:required => true
      = f.input :country, :as => :string, :required => true
      = f.input :zip_code, :label => "Postcode", :required => true
      %li
        = f.input :time_zone, :as => :time_zone, :collection => ActiveSupport::TimeZone.all.sort, :default => "Pacific Time (US & Canada)",
          :input_html => {:class => "time_zone_select"}

      -#%li
      -#  %label Billing Details
      -#  .billing_details
      -#    = link_to 'Update My Billing Details', customer_edit_billing_details_url

      .clearfix
      %h3 Change your password
      = f.input :password, :label => "New password"
      = f.input :password_confirmation, :label => "Confirm new password"
      = f.input :current_password, :hint => "(we need your current password to confirm your changes)"

      = f.submit "Update"

-#.infobar_right
-#  %h3 Cancel my account
-#
-#  %p
-#    Unhappy?
-#    = link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete

app/views/customer_registrations/edit_billing_details.html.haml
- content_for :extra_stylesheets do
  = stylesheet_link_tag "my5/base"

.content_left
  .padded
    %h1 Update my billing details

    = semantic_form_for current_customer, :as => :customer, :url => customer_update_billing_details_url do |f|

      %h3 Payment Details
      = f.inputs :for => :credit_card do |card|
        = card.input :card_number, :input_html => {:value => current_customer.card_number}
        = card.input :expiry_month, :collection => (1..12), :include_blank => false, :input_html => {:class => "short"}, :wrapper_html => { :class => "inline" }
        = card.input :expiry_year, :label => 'Year', :collection => (Time.now.year..10.years.from_now.year), :include_blank => false, :input_html => {:class => "short"}, :wrapper_html => { :class => "inline" }
        = card.input :name_on_card, :input_html => {:value => current_customer.card_name}
        = card.input :verification, :as => :password, :input_html => {:class => "short"}

      .actions
        = f.submit "Update"
        = link_to 'Back', edit_customer_registration_path

.infobar_right
  %h3 Remove my billing details

  %p
    Please click here to
    = link_to "delete your billing details", customer_remove_billing_details_path(), :confirm => "Are you sure?", :method => :put

app/views/customer_registrations/new.html.haml
.padded
  %h1 Sign up

  %h2 Join now for a free 10 day trial!
  %p After the initial 10 days, you will be charged $#{params[:promo_code_enabled] == "true" || (!params[:customer].nil? &&  !params[:customer][:promo_code].nil? && !params[:customer][:promo_code].blank?) ? payment_check(Program.second.try(:price)) :  payment_check(Program.first.try(:price))} for a yearly subscription.

  = semantic_form_for resource, :as => resource_name, :url => customer_confirm_details_url do |f|

    %h3 Account Details
    = f.inputs do
      = f.input :email
      = f.input :password
      = f.input :password_confirmation, :required => true, :label_html => {:class => "double-line"}
      %li
        = f.label :time_zone, "time zone"
        = f.time_zone_select('time_zone', ActiveSupport::TimeZone.all.sort, :default => "Sydney")

    %h3 Payment Details
    = f.radio_button :free_trial_opted, '1', :checked => true
    = label :free_trial_opted_yes, 'Free trial for 10 days'
    = f.radio_button :free_trial_opted, '0'
    = label :free_trial_opted_yes, 'Buy now'
    = f.inputs :for => :credit_card do |card|
      - if resource && (resource.errors[:credit_card].nil? || !resource.errors[:credit_card].empty?)
        %p.alert Please check your credit card details.
        = puts resource.errors
      = card.input :card_number
      = card.input :expiry_month, :label => 'Expiry Date', :collection => (1..12), :include_blank => false, :input_html => {:class => "short"}, :wrapper_html => { :class => "inline" }
      = card.input :expiry_year, :label => false, :collection => (Time.now.year..10.years.from_now.year), :include_blank => false, :input_html => {:class => "short"}, :wrapper_html => { :class => "inline" }
      = card.input :name_on_card
      = card.input :verification, :as => :password, :input_html => {:class => "short"}

    %h3 Billing Address
    = f.inputs do
      = f.input :title, :collection => ['Mr.', 'Ms.', 'Mrs.', 'Miss', 'Dr.', 'Sir.', 'Prof.'], :include_blank => false, :input_html => {:class => "short"}, :required => true
      = f.input :first_name, :required => true
      = f.input :last_name, :required => true
      = f.input :street_1, :required => true
      = f.input :street_2, :required => false
      = f.input :city, :required => true
      = f.input :state, :input_html => {:class => "short"}, :required => true
      = f.input :country, :input_html => {:class => "medium"}, :as => :hidden, :value => "AU"
      = f.input :zip_code, :label => "Postcode", :input_html => {:class => "short"}, :required => true

    - if (params[:promo_code_enabled] == "true" || (!params[:customer].nil? &&  !params[:customer][:promo_code].nil? && !params[:customer][:promo_code].blank?))
      = f.input :promo_code
    = f.input :accept_terms, :label => "I agree that I have read and understood the My 5 #{link_to 'terms and conditions', '/pages/terms-and-conditions', :target => :_blank, :class => 'green'}, including the medical warning.".html_safe, :label_html => {:style => 'width: 100%; margin-left: 0px;'}, :input_html => {:style => 'margin-left: 0px'}, :as => :boolean, :required => true

    .actions
      = render "devise/shared/links"