config/routes.rb
Semblance::Application.routes.draw do

# highcharts
  match 'refinery/reports/screen1' => 'refinery/reports#screen_1'
  match 'my5/dashboard/screen1' => 'my5/dashboard#screen_1'
  match 'refinery/reports/update_department' => 'refinery/reports#update_department'
  match 'my5/dashboard/update_department' => 'my5/dashboard#update_department'
  match 'my5_naturally/search' => 'blog/posts#search'

#excel
  match 'refinery/reports/download_excel' => 'refinery/reports#download_excel'
  match 'my5/dashboard/download_excel' => 'my5/dashboard#download_excel'


  devise_for :customers, :controllers => { :registrations => 'customer_registrations', :sessions => 'customer_sessions' }
  devise_scope :customer do
    post '/customers/confirm_details' => 'customer_registrations#confirm_details', :as => :customer_confirm_details
    get '/customers/success' => 'customer_registrations#confirmed_sign_up', :as => :customer_confirmed_sign_up
    get '/customers/edit/billing_details' => 'customer_registrations#edit_billing_details', :as => :customer_edit_billing_details
    put '/customers/update_billing_details' => 'customer_registrations#update_billing_details', :as => :customer_update_billing_details
    put '/customers/remove_billing_details' => 'customer_registrations#remove_billing_details', :as => :customer_remove_billing_details
    post 'upload_image' => 'customer_registrations#upload_image', :as => :upload_image
  end

  resources :emails, :only => [:create]
  resources :main_page_contact_form, :only => :create


  namespace :my5 do
    namespace :dashboard do
      get 'customer'
      get 'reports'
    end
    resources :departments, :except => [:show]
    resources :health_checkins, :except => [:show, :edit, :update]
    resources :reminder_emails, :except => [:show]
  end

  namespace :refinery do
    resources :reports, :only => [:index, :show], :controller => 'reports'
  end

  match 'dashboard' => 'my5/dashboard#customer'

  match 'refinery/customers/bulk-import' => 'refinery/customers#bulk_import', :as => "bulk_import_customers"
  match 'refinery/video_stats' => 'refinery/video_stats#index', :as => "refinery_video_stats"

  if Rails.env.development?
    mount SubscriptionsMailer::Preview => 'subscriptions_mailer'
    mount ReminderEmailMailer::Preview => 'reminder_emails_mailer'
  end

  root :to => "pages#show", :id => "home"
end

app/views/shared/_content_page.html.erb
<%
  # provide a default array for collecting CSS for sections
  css = []
  # if 'sections' is passed in as a local_assigns, all of this is ignored.
  if local_assigns[:sections].blank?
    # always have a title
    sections = [{:yield => :body_content_title, :fallback => page_title, :title => true}]

    # append sections from this page.
    @page.parts.inject(sections) do |s, part|
      # we have some default yields, body_content_left and body_content_right
      # these map to 'body' and 'side_body' fields in default Refinery.
      section = {:fallback => part.body}
      section[:yield] = case (title_symbol = part.title.to_s.gsub(/\ /, '').underscore.to_sym)
        when :body then :body_content_left
        when :side_body then :body_content_right
        else title_symbol
        end

      # add section to the list unless we were specifically requested not to.
      # otherwise, add css saying it's been removed.
      unless (local_assigns[:hide_sections]||=[]).include?(section[:yield])
        s << section
      else
        css << "no_#{section[:yield]}"
      end
    end unless @page.nil? or @page.parts.blank?

    # Ensure that even without @page.parts we still have body_content_left and body_content_right
    all_yields = sections.collect{|s| s[:yield]}
    sections << {:yield => :body_content_left} unless all_yields.include?(:body_content_left)
    sections << {:yield => :body_content_right} unless all_yields.include?(:body_content_right)
  end

  # you can add more sections to the list using something like this:
  # sections |= [{:yield => :something_else, :fallback => another_method, :id => 'something'}]

  sections.each do |section|
    section[:html] = yield(section[:yield]) if section[:yield].present?

    if section[:html].blank? and !local_assigns[:show_empty_sections] and
       !local_assigns[:remove_automatic_sections] and section.keys.include?(:fallback) and
       section[:fallback].present?
      section[:html] = raw(section[:fallback])
    end

    dom_id = section[:id] || section[:yield]
    if section[:html].present?
      if section[:title]
        section[:html] = "<h1 id='#{dom_id}'>#{section[:html]}</h1>".html_safe
      else
        section[:html] = "<div id='#{dom_id}'><div class='inner'>#{section[:html]}</div></div>".html_safe
      end
    else
      css << "no_#{dom_id}"
    end
  end
-%>
<div id='body_content'<%= " class='#{css.join(' ')}'" if css.present? %>>
  <%= raw sections.map{|section| section[:html]}.join("\n") -%>
  <%= render :partial => "/shared/my5_custom_page_images", :locals => {:title => @page.title} %>
</div>
<%= render :partial => '/shared/draft_page_message' unless @page.nil? or @page.live? -%>

app/views/shared/_footer.html.haml
%nav
    %ul.titles
        %li.first= link_to "Features", page_path("features")
        %li= link_to "Services", page_path("services")
        %li= link_to "Pricing", page_path("pricing")
        %li= link_to "About Us", page_path("about")
        %li= link_to "Contact us", page_path("contact-us")
    %ul.first
        %li= link_to "Key features", page_path("features")
        %li= link_to "The Workplace", page_path("workplace")
    %ul
        %li= link_to "Our Services", page_path("services")
    %ul
        %li= link_to "Individual", page_path("pricing")
        %li.double-line= link_to "Corporate and Enterprise", page_path("corporate-and-enterprise-membership")
    %ul
        %li= link_to "Vision", page_path("vision")
        %li= link_to "Values", page_path("values")
        %li= link_to "People", page_path("people")
        %li= link_to "The My 5 Team", page_path("tim-norris")
        %li= link_to "Testimonials", page_path("testimonials")
        %li= link_to "Careers", page_path("careers")
        %li= link_to "Terms and Conditions", page_path("terms-and-conditions")
        %li= link_to "Privacy Policy", page_path("privacy-policy")
    %ul
        %li= link_to "Get in touch", page_path("contact-us")
    %ul.last
        - if current_customer
            %li= link_to "Sign out", destroy_customer_session_path
%div#line My 5 Pty Ltd | ABN: 19 121 460517
%div#logo= image_tag "logo.png"

app/views/shared/_head.html.haml
%title= page_title
= render 'shared/javascripts'
= render 'shared/stylesheets', :include_common => include_common
= csrf_meta_tag

:javascript
  $(document).ready(function () {
              $('#department_id').dropdownchecklist({ width: 188, maxDropHeight: 150 });
              $('#role_id').dropdownchecklist({ width: 188, maxDropHeight: 150 });
              $('#city').dropdownchecklist({ width: 188, maxDropHeight: 150 });
              $('#state').dropdownchecklist({ width: 188, maxDropHeight: 150 });
              $('#state2').dropdownchecklist({ width: 188, maxDropHeight: 150 });
              $('#country').dropdownchecklist({ width: 188, maxDropHeight: 150 });
          });

app/views/shared/_header.html.haml
%div#logo= link_to image_tag("logo.png"), root_path
%div#smoothmenu.ddsmoothmenu
	%ul
		- Page.where(:show_in_menu => true).where("parent_id = 1").order("-custom_position DESC, id ASC").each do |p|
			%li
				= link_to p.title, page_path(p)
		%li
			= link_to "Sign In", new_customer_session_path, :class => "green_button"
			= link_to "Company Sign In", new_customer_session_path(:company_login => true), :class => "blue_button"
#bars.top

app/views/shared/_javascripts.html.haml
= javascript_include_tag 'jquery.min', 'jquery_ujs','jquery-ui-1.7.1.custom.min'
= javascript_include_tag :defaults, :cache => true
-#= javascript_include_tag 'my5/lib/ddsmoothmenu'
-#= javascript_include_tag 'chosen.jquery'
= javascript_include_tag 'refinery/ui.dropdownchecklist-1.4-min'
= javascript_include_tag 'js_for_graph'
= javascript_include_tag 'foundation'
= javascript_include_tag 'foundation.forms'
= javascript_include_tag 'blog/blog'
= yield :extra_js

app/views/shared/_stylesheets.html.haml
= stylesheet_link_tag 'common', :media => 'screen, projection' if include_common
= stylesheet_link_tag :head, params
= stylesheet_link_tag 'refinery/ui.dropdownchecklist.standalone'
= stylesheet_link_tag 'my5/dashboard/chosen'
= stylesheet_link_tag 'my5/blog/print', :media => 'print'

= yield :extra_stylesheets